services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crow-app
    ports:
      - "${PORT_HTTP:-80}:8080"
    volumes:
      # CAMBIO: Usamos una carpeta local './data' en el host para la base de datos
      - ./data:/database
      # Mantenemos el montaje de estáticos si lo necesitas para desarrollo
      - ./backend/src/frontend:/app/static 
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${BACKEND_MEMORY_LIMIT:-32M}
          cpus: '1' 
        reservations:
          memory: ${BACKEND_RESERVATIONS:-16M}
    environment:
      - LOG_LEVEL=info
      # El binario buscará el archivo dentro de la ruta montada
      - DB_PATH=/database/app.db

